# -*- coding: utf-8 -*-
"""DeepLearn_ActivationFunctions.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1b1R8qIs4qtrMY_HZVe1mNA9e_QDudcm5
"""

import sys,os
sys.path.append(os.pardir)
import numpy as np
from common.layers import *



